### ISSUE TITLE
Drupal 8.8.0 : TypeError: Argument 2 passed to Drupal\page_cache\StackMiddleware\PageCache::storeResponse()

### ISSUE THREAD

**Issue by Marek-Zientek** [litespeedtech/lscache-drupal#12]
When I try to log in I get the following message:
The website encountered an unexpected error. Please try again later.
TypeError: Argument 2 passed to Drupal\page_cache\StackMiddleware\PageCache::storeResponse() must be an instance of Symfony\Component\HttpFoundation\Response, null given, called in /home/naukispo/domains/nauki-spoleczne.info/public_html/core/modules/page_cache/src/StackMiddleware/PageCache.php on line 195 in Drupal\page_cache\StackMiddleware\PageCache->storeResponse() (line 212 of core/modules/page_cache/src/StackMiddleware/PageCache.php).

I use litespeed and memcached.

**Comment by lupupitkanen** [comment]
That error is from the Internal Page Cache module (page-cache), not from lscache module.

I think you should disable the internal page cache module if you are using the LSCache module.

**Comment by lupupitkanen** [comment]
I'm quite sure this is a duplicate of #10 and should be closed.

**Comment by Woet** [comment]
Duplicate of #10
