### ISSUE TITLE
Drupal 9 compability

### ISSUE THREAD

**Issue by saschaeggi** [litespeedtech/lscache-drupal#14]
Please fix the following to be compatible with Drupal 9:
`modules/contrib/lscache/src/Form/LSCacheForm.php | 167 | Call to deprecated function drupal_set_message(). Deprecated in drupal:8.5.0 and is removed from drupal:9.0.0. Use Drupal\Core\Messenger\MessengerInterface::addMessage() instead.
`

`modules/contrib/lscache/src/Form/LSCacheForm.php | 175 | Call to deprecated function drupal_set_message(). Deprecated in drupal:8.5.0 and is removed from drupal:9.0.0. Use Drupal\Core\Messenger\MessengerInterface::addMessage() instead.`

**Comment by saschaeggi** [comment]
See PR: https://github.com/litespeedtech/lscache-drupal/pull/16

**Comment by Woet** [comment]
Already fixed, refer to #16
