### ISSUE TITLE
Is there a Drupal 7 version available of this module?

### ISSUE THREAD

**Issue by umed1991** [litespeedtech/lscache-drupal#18]
We have a drupal 7 website where we want to try LiteSpeed server as performance is key for us. Our website is on Drupal 7 version so is there a Drupal 7 version of this module available?

**Comment by lupupitkanen** [comment]
No, I don't think so. The cache infrastructure of Drupal 7 does not allow same kind of functionality that is possible with this module and Drupal 8. Please see LiteSpeed documentation about running Drupal 7 without a module:

https://www.litespeedtech.com/support/wiki/doku.php/litespeed_wiki:cache:no-plugin-drupal-7
