### ISSUE TITLE
Drupal 10 compatibility

### ISSUE THREAD

**Issue by redseujac75** [litespeedtech/lscache-drupal#29]
Is this module compatible with Drupal 10 ?

If not please update asap.

**Comment by pawelek-org** [comment]
Latest version of [lscache-drupal](https://github.com/litespeedtech/lscache-drupal) is not compatible with Drupal 10.
I've just tested with Druval 10.0.4 @ php8.2 and it's not working.

**Comment by jefflogan303** [comment]
I've created a pull request which can be tested, and hopefully merged.

https://github.com/litespeedtech/lscache-drupal/pull/30

**Comment by Code-Egg** [comment]
Thanks, it works and merged. Close the issue
